[package]
name = "devsec"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive", "env"] }
color-eyre = "0.6.3"
crossterm = "0.28.1"
dotenvy = "0.15"
governor = "0.8.0"
hyper = { version = "1", features = ["full"] }
indicatif = "0.17"
rand = "0.9"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = ["chrono", "postgres", "runtime-tokio"] }
tokio = { version = "1", features = ["full"] }
