[package]
name = "devsec"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive", "env"] }
dotenvy = "0.15"
governor = "0.8.0"
hyper = { version = "1", features = ["full"] }
indicatif = "0.17"
nonzero_ext = "0.3.0"
reqwest = { version = "0.12", features = ["json"] }
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "chrono",
    "bigdecimal",
] }
tabled = { version = "0.17.0", features = ["ansi"] }
tokio = { version = "1", features = ["full"] }
